### PR TITLE
Authorization headers Basic Auth

### PR DESCRIPTION
**Pull request by ghost**
Hi, I am done with changes. Sorry it took so long, I was bogged with some stuff in erlang that last while. I ran tests but haven't yet created any new tests for the authentication which should be done.

Regards,
David

### CODE REVIEW

**Comment by tdebarochez** [comment]
ok, waiting for tests.

**Comment by ghost** [comment]
Sure, will write the tests and send you updated pull. The tests will assume a clean unsecured couchdb instance (ie no admin setup) and will each test will set up user and test each action ie get, put, del as authenticated user. These tests will follow the basic tests that assume no authentication.

Regards,
David

**Comment by ghost** [comment]
Hi. One thing missing here is to add admin programmatically to authorized readers list for the database/used for sessions. I will add this in. Without this, although SSL, any user with access to db could read sessions data which is not desirable.

**Comment by ghost** [comment]
Sorry accidentally closed pull request. Don't want to do that :-) Anyway, working away at tests.

**Comment by ghost** [comment]
old issue

**Pull request closed without merging**
