### PR TITLE
Issue #22: Simplify the expires view

### PR DESCRIPTION
**Pull request by qraynaud**
Here is the pull request corresponding to the changes discussed in Issue #22. There is no new test or changes in the tests because I didn't moved the API at all. This is only an internal optimization.

### CODE REVIEW

**Comment by tdebarochez** [comment]
Thanks a lot for your pull request, but Travis builds are [broken](https://travis-ci.org/tdebarochez/connect-couchdb/builds/5755803). 
Does it works for you ?

**Comment by qraynaud** [comment]
Yes, all tests are fine on my side. Looking at the logs, it seems to me there is an issue connecting to Couch (I didn't modified any code related to this). Maybe the couch server the build system is using was down at the time of testing?

**Comment by qraynaud** [comment]
Here is the log for the tests using my build :

```
~/Projects/connect-couchdb$ npm test

> connect-couchdb@0.3.0 test /media/data/Documents/quentin/Projects/connect-couchdb
> NODE_ENV=test expresso test/test.*.js

path.existsSync is now called `fs.existsSync`.

   100% 5 tests

```

**Comment by tdebarochez** [comment]
Weird... It works here.

**Pull request merged**
