### PR TITLE
reduces PUT-requests by fixing a looping condition

### PR DESCRIPTION
**Pull request by alappe**
This fixes a broken looping condition (because doc.sess.lastAccess is explicitly set to null several lines above) that caused issued PUT-requests on every check for cookie lifetime…

The test ensures that the PUT is not done if the cookie is still alive (though the style of the test is debatable… decide if you want it like this…).

### CODE REVIEW

**Comment by alappe** [comment]
Sorry, I just saw you fixed this in d011c6a221d8e7c some hours ago… nevermind then…

**Comment by tdebarochez** [comment]
Yes, but I am still interested by your test case. May I merge it ?

**Comment by alappe** [comment]
Of course…

**Comment by tdebarochez** [comment]
Thanks

**Comment by alappe** [comment]
You're welcome…

**Pull request closed without merging**
